# SPDX-FileCopyrightText: (c) 2022-2023 Siemens
# SPDX-License-Identifier: MIT

name: Build documentation and deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          # WARNING: The scripts sphinx-apidoc, sphinx-autogen, sphinx-build and sphinx-quickstart are installed in '/home/runner/.local/bin' which is not on PATH.

      - name: Build documentation
        run: |
          # use sphinx to build the documentation
          sphinx-build -b html ./docs-source ./docs
